### PR TITLE
Implements #22: Add Ping command to remote location

### PR DESCRIPTION
**Pull request by mattfarina**
@sdboyer does this work for you?

### CODE REVIEW

**Comment by sdboyer** [comment]
Yeah, that looks about like what I had in mind.

The only note...for bzr, how would you feel about checking to see if it's a launchpad addr, and if it is, then just hitting launchpad's web http API to see if that side project exists? I'm not sure how much effort would be needed to make sure that their response is indicative of a real project being present, but...still, that might be much faster.

Doesn't have to be done here, though - can easily and transparently be done in a follow-up.

**Comment by sdboyer** [comment]
Although, we should keep our eye on `git ls-remote` as the approach for git. Some hosts do disable it, which could be misleading. (It is the fastest remote-touching op I can immediately think of, though; any decent host will have all the information in the `packed-refs` file, so it's basically just streaming that file straight back to the caller).

**Comment by mattfarina** [comment]
For what it's worth, these are the commands that `go` uses when it need to ping an endpoint.

**Comment by sdboyer** [comment]
Ah, I didn't know that `ls-remote` was what they use. Well, that's reassuring on the "hosts probably support it well enough" front, as it means we've all been effectively testing it by using `go get`.

As you noted in your own comment on the bzr command, though - just because it was fast enough for `go get`, doesn't mean it's fast enough for us/for a solver. Different use case, different requirements.

**Comment by sdboyer** [comment]
But, all that's just nitty detail - like I said, this fundamentally LGTM

**Comment by sdboyer** [comment]
@mattfarina ooh, if that works, then yeah, that LGTM

**Pull request merged**
