### PR TITLE
Add support for initializing git repositories

### PR DESCRIPTION
**Pull request by tony**
Useful for cases when testing repos.

I'll be using this and #25 in https://github.com/tony/vcsync on making a golang version of www.github.com/tony/vcspull.

### CODE REVIEW

**Comment by mattfarina** [comment]
@tony Thanks for the PR. One of the goals of this project is to enable working across multiple VCS. In addition to Git it needs to support Bzr, Hg, and Svn. We can talk about what an Svn solution would need to be since it's not quite the same. Can you add for these other VCS?

**Comment by tony** [comment]
@mattfarina rebased, updated with initialization support for bzr, hg and svn initialization.

**Comment by mattfarina** [comment]
@tony thanks for the update. I noticed there are no tests for any of these. Would you mind adding tests?

**Comment by tony** [comment]
@mattfarina try now

**Comment by mattfarina** [comment]
@tony thanks for the contribution.

**Pull request merged**
